
services:
  postgres:
    image: postgres:17.4-alpine
    container_name: church-maintenance-db
    environment:
      POSTGRES_DB: maintenance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d maintenance"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
